/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.books.ui.manager;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.books.dao.NguoiDungSDDAO;
import poly.books.entity.NguoiDungSD;

/**
 *
 * @author Thuy
 */
public class QLTaiKhoan extends javax.swing.JPanel implements poly.books.controller.NguoiDungSDController{
    List<NguoiDungSD> listndsd=new ArrayList<>();
    NguoiDungSDDAO ndsddao=new NguoiDungSDDAO();
    public QLTaiKhoan() {
        initComponents();
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        QLTK = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        btnThemTaiKhoan = new javax.swing.JButton();
        btnSuaTaiKhoan = new javax.swing.JButton();
        btnXoaTaiKhoan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        txtTendangnhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtHovaten = new javax.swing.JTextField();
        rdoConLam = new javax.swing.JRadioButton();
        rdoNghiLam = new javax.swing.JRadioButton();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1123, 773));
        setPreferredSize(new java.awt.Dimension(1123, 773));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 144, 193));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(246, 50));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        QLTK.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tên đăng nhập");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Họ và tên");

        jLabel5.setText("Trạng thái");

        jLabel6.setText("Quản lý");

        jLabel7.setText("Hình ảnh");

        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_supplier_25px.png"))); // NOI18N
        lblAnh.setText("ảnh");
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMouseClicked(evt);
            }
        });

        btnThemTaiKhoan.setBackground(new java.awt.Color(255, 153, 153));
        btnThemTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons8_add_25px_5.png"))); // NOI18N
        btnThemTaiKhoan.setText("Thêm");
        btnThemTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTaiKhoanActionPerformed(evt);
            }
        });

        btnSuaTaiKhoan.setBackground(new java.awt.Color(255, 255, 204));
        btnSuaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons8_edit_25px.png"))); // NOI18N
        btnSuaTaiKhoan.setText("Sửa");
        btnSuaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTaiKhoanActionPerformed(evt);
            }
        });

        btnXoaTaiKhoan.setBackground(new java.awt.Color(51, 255, 255));
        btnXoaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/book/icons8_delete_25px_1.png"))); // NOI18N
        btnXoaTaiKhoan.setText("Xoá");
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 204, 204));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_reset_25px_1.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên đăng nhập", "Mật khẩu", "Họ và tên", "Trạng thái", "Quản lý", "Hình ảnh"
            }
        ));
        jScrollPane1.setViewportView(tblTaiKhoan);

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoConLam);
        rdoConLam.setText("Còn làm");

        buttonGroup1.add(rdoNghiLam);
        rdoNghiLam.setText("Nghỉ làm");

        buttonGroup2.add(rdoQuanLy);
        rdoQuanLy.setText("Quản lý");

        buttonGroup2.add(rdoNhanVien);
        rdoNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout QLTKLayout = new javax.swing.GroupLayout(QLTK);
        QLTK.setLayout(QLTKLayout);
        QLTKLayout.setHorizontalGroup(
            QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QLTKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QLTKLayout.createSequentialGroup()
                            .addComponent(btnThemTaiKhoan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QLTKLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(40, 40, 40)
                            .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(QLTKLayout.createSequentialGroup()
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QLTKLayout.createSequentialGroup()
                                .addComponent(rdoQuanLy)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNhanVien))
                            .addGroup(QLTKLayout.createSequentialGroup()
                                .addComponent(rdoConLam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoNghiLam))
                            .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTendangnhap)
                                .addComponent(txtMatKhau)
                                .addComponent(txtHovaten, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))))
                .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QLTKLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnXoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnLamMoi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QLTKLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        QLTKLayout.setVerticalGroup(
            QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QLTKLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QLTKLayout.createSequentialGroup()
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rdoConLam)
                            .addComponent(rdoNghiLam))
                        .addGap(63, 63, 63)
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rdoQuanLy)
                            .addComponent(rdoNhanVien))
                        .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QLTKLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(QLTKLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))
                    .addGroup(QLTKLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addGroup(QLTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTaiKhoan)
                    .addComponent(btnSuaTaiKhoan)
                    .addComponent(btnXoaTaiKhoan)
                    .addComponent(btnLamMoi))
                .addGap(66, 66, 66))
        );

        jPanel1.add(QLTK, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getName();
            File destDir = new File("src/main/resources/New folder (2)"); // Thư mục tài nguyên
            if (!destDir.exists()) {
                destDir.mkdirs();
            }
            File dest = new File(destDir, fileName);
            try {
                Files.copy(selectedFile.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Không thể sao chép ảnh: " + ex.getMessage());
                return;
            }
            lblAnh.setToolTipText(fileName); // Lưu tên file
            lblAnh.setText("");

            // Tải và thu nhỏ ảnh theo kích thước của lblanh
            java.net.URL imageUrl = getClass().getResource("/New folder (2)/" + fileName);
            if (imageUrl != null) {
                ImageIcon icon = new ImageIcon(imageUrl);
                Image img = icon.getImage().getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
                lblAnh.setIcon(new ImageIcon(img));
            } else {
                lblAnh.setText("Không tải được ảnh");
            }
        }
    }//GEN-LAST:event_lblAnhMouseClicked

    private void btnThemTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTaiKhoanActionPerformed
        this.create();
    }//GEN-LAST:event_btnThemTaiKhoanActionPerformed

    private void btnSuaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTaiKhoanActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaTaiKhoanActionPerformed

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        this.clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QLTK;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaTaiKhoan;
    private javax.swing.JButton btnThemTaiKhoan;
    private javax.swing.JButton btnXoaTaiKhoan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JRadioButton rdoConLam;
    private javax.swing.JRadioButton rdoNghiLam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTendangnhap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(NguoiDungSD ndsd) {
        txtTendangnhap.setText(String.valueOf(ndsd.getTenDangNhap()));
        txtMatKhau.setText(String.valueOf(ndsd.getMatKhau()));
        txtHovaten.setText(String.valueOf(ndsd.getHoTen()));
        
        if (ndsd.isTrangThai()) {
            rdoConLam.setSelected(true);
        } else {
            rdoNghiLam.setSelected(true);
        }

        if (ndsd.isQuanLy()) {
            rdoQuanLy.setSelected(true);
        } else {
            rdoNhanVien.setSelected(true);
        }
        
        lblAnh.setIcon(null);
            lblAnh.setText("");
            if (ndsd.getHinhAnh() != null && !ndsd.getHinhAnh().isEmpty()) {
                lblAnh.setToolTipText(ndsd.getHinhAnh());
                java.net.URL imageUrl = getClass().getResource("/New folder (2)/" + ndsd.getHinhAnh());
                if (imageUrl != null) {
                    ImageIcon icon = new ImageIcon(imageUrl);
                    Image img = icon.getImage().getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
                    lblAnh.setIcon(new ImageIcon(img));
                }
            }
    }

    @Override
    public NguoiDungSD getForm() {
        NguoiDungSD nd = new NguoiDungSD();
        nd.setTenDangNhap(txtTendangnhap.getText().trim());
        nd.setMatKhau(new String(txtMatKhau.getText()).trim());
        nd.setHoTen(txtHovaten.getText().trim());

        nd.setTrangThai(rdoConLam.isSelected());
        nd.setQuanLy(rdoQuanLy.isSelected());

        nd.setHinhAnh(lblAnh.getToolTipText()); // giả sử bạn dùng toolTipText để lưu tên file ảnh
        return nd;
    }

    @Override
    public void fillToTable() {
        DefaultTableModel defaultTableModel=(DefaultTableModel) tblTaiKhoan.getModel();
        defaultTableModel.setRowCount(0);
        listndsd=ndsddao.findAll();
        for(NguoiDungSD ndsd:listndsd){
           defaultTableModel.addRow(new Object[]{
            ndsd.getTenDangNhap(),
            ndsd.getMatKhau(),
            ndsd.getHoTen(),
            ndsd.isTrangThai() ? "Còn làm" : "Nghỉ làm",
            ndsd.isQuanLy() ? "Quản lý" : "Nhân viên",
            ndsd.getHinhAnh()
        }); 
        }
    }

    @Override
    public void create() {
        NguoiDungSD nd = getForm();
    if (nd == null) return;

    try {
        ndsddao.craete(nd);
        fillToTable();
        clear();
        JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại!");
    }
    }

    @Override
    public void update() {
        NguoiDungSD nd = getForm();
    if (nd == null) return;

    try {
        ndsddao.update(nd);
        fillToTable();
        clear();
        JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thành công!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thất bại!");
    }
    }

    @Override
    public void delete() {
         String tendangnhap = txtTendangnhap.getText();
    if (tendangnhap.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để xóa!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tài khoản này?");
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            ndsddao.detele(tendangnhap);
            fillToTable();
            clear();
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thất bại!");
        }
    }
    }

    @Override
    public void clear() {
        txtTendangnhap.setText("");
        txtMatKhau.setText("");
        txtHovaten.setText("");
        rdoConLam.setSelected(true);
         rdoNghiLam.setSelected(true);
         lblAnh.setIcon(null);
        lblAnh.setToolTipText(null);
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
