/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.books.ui;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import poly.books.controller.PolybookController;
import poly.books.dao.impl.UserDAOImpl;
import poly.books.entity.NguoiDungSD;
import poly.books.util.XAuth;
import poly.books.util.XIcon;

/**
 *
 * @author HuyNguyen
 */
public class Book extends javax.swing.JFrame implements poly.books.controller.PolybookController {

    public CardLayout cardLayout;

    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
        init();
        banHang.setParentFrame(this);
        addClickEffect(lbBanHang);
        addClickEffect(lbQLSach);
        addClickEffect(lbTaiKhoan);
        addClickEffect(lbQuanLyKH);
        addClickEffect(lbThongKe);
        addClickEffect(lbgiamgia);
        addClickEffect(lbDangXuat);
        addClickEffect(lbDoiMk);
        addClickEffect(lbLichSu);
        cardLayout = (CardLayout) QuanLy.getLayout();
    }

    private void showThongKe() {

        // Tạo instance của QuanLySach và lấy nội dung
        ThongKe QlTK = new ThongKe(this, false); // Không cần modal
        JPanel contentPanel = QlTK.getContentPanel();

        // Thêm nội dung vào mainSach
        pnlThongke.setLayout(new BorderLayout());
        pnlThongke.add(contentPanel, BorderLayout.CENTER);
        pnlThongke.revalidate();
        pnlThongke.repaint();
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Book = new javax.swing.JSplitPane();
        menu = new poly.books.util.GradientPanel()
        ;
        lbBanHang = new javax.swing.JLabel();
        lbQLSach = new javax.swing.JLabel();
        lbTaiKhoan = new javax.swing.JLabel();
        lbQuanLyKH = new javax.swing.JLabel();
        lbThongKe = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lbgiamgia = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        lbDoiMk = new javax.swing.JLabel();
        lbLichSu = new javax.swing.JLabel();
        QuanLy = new javax.swing.JPanel();
        banHang = new poly.books.ui.BanHang();
        quanLyKhachHang1 = new poly.books.ui.manager.QuanLyKhachHang();
        lichSu1 = new poly.books.ui.LichSu();
        qLTaiKhoan1 = new poly.books.ui.manager.QLTaiKhoan();
        quanLySach1 = new poly.books.ui.manager.QuanLySach();
        changePassword1 = new poly.books.ui.ChangePassword();
        qlThongKe = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlThongke = new javax.swing.JPanel();
        quanLyPhieuGiamGia1 = new poly.books.ui.manager.QuanLyPhieuGiamGia();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1323, 800));

        Book.setBackground(new java.awt.Color(255, 255, 255));
        Book.setDividerSize(0);
        Book.setEnabled(false);
        Book.setMinimumSize(new java.awt.Dimension(1323, 800));
        Book.setOpaque(false);
        Book.setPreferredSize(new java.awt.Dimension(1323, 800));

        menu.setBackground(new java.awt.Color(0, 204, 204));
        menu.setMinimumSize(new java.awt.Dimension(200, 773));
        menu.setPreferredSize(new java.awt.Dimension(200, 773));

        lbBanHang.setBackground(new java.awt.Color(51, 51, 255));
        lbBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        lbBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBanHang.setText("Bán Hàng");
        lbBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBanHangMouseClicked(evt);
            }
        });

        lbQLSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbQLSach.setForeground(new java.awt.Color(255, 255, 255));
        lbQLSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQLSach.setText("Quản lý sách");
        lbQLSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQLSachMouseClicked(evt);
            }
        });

        lbTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lbTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTaiKhoan.setText("Tài khoản");
        lbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTaiKhoanMouseClicked(evt);
            }
        });

        lbQuanLyKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbQuanLyKH.setForeground(new java.awt.Color(255, 255, 255));
        lbQuanLyKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanLyKH.setText("Quản lý khách hàng");
        lbQuanLyKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyKHMouseClicked(evt);
            }
        });

        lbThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongKe.setText("Thống kê");
        lbThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThongKeMouseClicked(evt);
            }
        });

        lblAnh.setBackground(new java.awt.Color(51, 51, 255));
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lblHoTen.setText("Tên ");

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVu.setText("Chức vụ");

        lbgiamgia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbgiamgia.setForeground(new java.awt.Color(255, 255, 255));
        lbgiamgia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbgiamgia.setText("Giảm giá");
        lbgiamgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbgiamgiaMouseClicked(evt);
            }
        });

        lbDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lbDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangXuat.setText("Đăng xuất");
        lbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseClicked(evt);
            }
        });

        lbDoiMk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDoiMk.setForeground(new java.awt.Color(255, 255, 255));
        lbDoiMk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDoiMk.setText("Đổi Mật Khẩu");
        lbDoiMk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDoiMkMouseClicked(evt);
            }
        });

        lbLichSu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLichSu.setForeground(new java.awt.Color(255, 255, 255));
        lbLichSu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLichSu.setText("Lịch Sử");
        lbLichSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLichSuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbQLSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbgiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbDoiMk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbQuanLyKH, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(lbLichSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQLSach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbQuanLyKH, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbgiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLichSu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDoiMk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        Book.setLeftComponent(menu);

        QuanLy.setBackground(new java.awt.Color(255, 255, 255));
        QuanLy.setMinimumSize(new java.awt.Dimension(1123, 800));
        QuanLy.setPreferredSize(new java.awt.Dimension(1123, 800));
        QuanLy.setLayout(new java.awt.CardLayout());
        QuanLy.add(banHang, "card2");
        QuanLy.add(quanLyKhachHang1, "card3");
        QuanLy.add(lichSu1, "card5");
        QuanLy.add(qLTaiKhoan1, "card6");
        QuanLy.add(quanLySach1, "card7");
        QuanLy.add(changePassword1, "card8");

        qlThongKe.setLayout(new java.awt.BorderLayout());

        jLabel9.setBackground(new java.awt.Color(0, 144, 193));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thống Kê");
        jLabel9.setMinimumSize(new java.awt.Dimension(82, 50));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(82, 50));
        qlThongKe.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        pnlThongke.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlThongkeLayout = new javax.swing.GroupLayout(pnlThongke);
        pnlThongke.setLayout(pnlThongkeLayout);
        pnlThongkeLayout.setHorizontalGroup(
            pnlThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        pnlThongkeLayout.setVerticalGroup(
            pnlThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        qlThongKe.add(pnlThongke, java.awt.BorderLayout.CENTER);

        QuanLy.add(qlThongKe, "card9");
        QuanLy.add(quanLyPhieuGiamGia1, "card4");

        Book.setRightComponent(QuanLy);

        getContentPane().add(Book, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbQLSachMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbQLSachMouseClicked
        cardLayout.show(QuanLy, "card7");

    }// GEN-LAST:event_lbQLSachMouseClicked

    private void lbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbTaiKhoanMouseClicked
        cardLayout.show(QuanLy, "card6");

    }// GEN-LAST:event_lbTaiKhoanMouseClicked

    private void lbQuanLyKHMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbQuanLyKHMouseClicked
        cardLayout.show(QuanLy, "card3");

    }// GEN-LAST:event_lbQuanLyKHMouseClicked


    private void lbThongKeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbThongKeMouseClicked
        showThongKe();
        cardLayout.show(QuanLy, "card9");
    }// GEN-LAST:event_lbThongKeMouseClicked

    private void lbgiamgiaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbgiamgiaMouseClicked
        cardLayout.show(QuanLy, "card4");

    }// GEN-LAST:event_lbgiamgiaMouseClicked

    private void lbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbDangXuatMouseClicked
        XAuth.user = null;
        System.exit(0);
    }// GEN-LAST:event_lbDangXuatMouseClicked

    private void lbDoiMkMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbDoiMkMouseClicked
        cardLayout.show(QuanLy, "card8");

    }// GEN-LAST:event_lbDoiMkMouseClicked

    private void lbLichSuMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbLichSuMouseClicked
        cardLayout.show(QuanLy, "card5");

    }// GEN-LAST:event_lbLichSuMouseClicked

    private void lbBanHangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbBanHangMouseClicked
        cardLayout.show(QuanLy, "card2");
    }// GEN-LAST:event_lbBanHangMouseClicked

    private JLabel selectedLabel = null;

    private void addClickEffect(JLabel label) {

        Color colorEnd = new Color(88, 169, 198);

        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (selectedLabel != null) {
                    selectedLabel.setBackground(null);
                    selectedLabel.setOpaque(false);
                    selectedLabel.setForeground(Color.WHITE);
                }
                label.setBackground(colorEnd);
                label.setForeground(Color.WHITE);
                label.setOpaque(true);
                selectedLabel = label;
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Book;
    public javax.swing.JPanel QuanLy;
    public poly.books.ui.BanHang banHang;
    private poly.books.ui.ChangePassword changePassword1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbBanHang;
    private javax.swing.JLabel lbDangXuat;
    private javax.swing.JLabel lbDoiMk;
    private javax.swing.JLabel lbLichSu;
    private javax.swing.JLabel lbQLSach;
    private javax.swing.JLabel lbQuanLyKH;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JLabel lbgiamgia;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblHoTen;
    public poly.books.ui.LichSu lichSu1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel pnlThongke;
    public poly.books.ui.manager.QLTaiKhoan qLTaiKhoan1;
    public javax.swing.JPanel qlThongKe;
    public poly.books.ui.manager.QuanLyKhachHang quanLyKhachHang1;
    private poly.books.ui.manager.QuanLyPhieuGiamGia quanLyPhieuGiamGia1;
    public poly.books.ui.manager.QuanLySach quanLySach1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void init() {
        this.setIconImage(XIcon.getIcon("/images/logo.png").getImage());
        this.setLocationRelativeTo(null);
        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);
        UserDAOImpl userDAO = new UserDAOImpl();

        if (XAuth.user == null) {
            System.out.println("No user logged in!");
            lblHoTen.setText("Chưa đăng nhập");
            lblChucVu.setText("Không xác định");
            return;
        }

        String tenDangNhap = XAuth.user.getTenDangNhap();
        System.out.println("Initializing user: " + tenDangNhap);
        NguoiDungSD user = userDAO.findById(tenDangNhap);
        if (user != null) {
            lblAnh.setIcon(null);
            lblAnh.setText("");
            if (user.getHinhAnh() != null && !user.getHinhAnh().isEmpty()) {
                lblAnh.setToolTipText(user.getHinhAnh());
                java.net.URL imageUrl = getClass().getResource("/imgTaiKhoan/" + user.getHinhAnh());
                if (imageUrl != null) {
                    ImageIcon icon = new ImageIcon(imageUrl);
                    Image img = icon.getImage().getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
                    lblAnh.setIcon(new ImageIcon(img));
                }
            }
            lblHoTen.setText(user.getHoTen());
            lblChucVu.setText(user.isQuanLy() ? "Quản lý" : "Nhân viên");

            if (!user.isQuanLy()) {
                lbQLSach.setVisible(false);
                lbTaiKhoan.setVisible(false);
                lbgiamgia.setVisible(false);
                lbThongKe.setVisible(false);
            }
        } else {
            System.out.println("User not found in database: " + tenDangNhap);
            lblHoTen.setText("Không tìm thấy người dùng");
            lblChucVu.setText("Không xác định");
        }
    }

    @Override
    public void exit() {
        PolybookController.super.exit(); // Generated from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void showJDialog(JDialog dialog) {
        PolybookController.super.showJDialog(dialog); // Generated from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void showWelcomeJDialog(JFrame frame) {
        PolybookController.super.showWelcomeJDialog(frame); // Generated from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void showLoginJDialog(JFrame frame) {
        PolybookController.super.showLoginJDialog(frame); // Generated from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

}
